### ISSUE TITLE
Crash when joining a world

### ISSUE THREAD

**Issue by emanuele246gi** [AlasDiablo/Diabolo-Lib#1]
Here there is the crash report: https://pastebin.com/J6VNhi01

Forge version: 41.1.0
Minecraft version: 1.19
Diabolo version: 5.5.27

**Comment by AlasDiablo** [comment]
Hello, for now DiaboloLib is the only mod available in 1.19 and is adding nothing expected core code required by my mod. Normally you can delete them from your modpack without issues.
Note: DiaboloLib for 1.19 use a very old version of forge 41.0.45, 68 version of forge have been release since.

**Comment by AlasDiablo** [comment]
One more thing, i see from your issue and the forge site, since yesterday a stable version have been release, I will try to update my mods for 1.19 (i dont no if this will be quick or not).

**Comment by emanuele246gi** [comment]
Don't worry man, I appreciate your efforts anyway. Also, I know that it's your only mod available for 1.19, but I prepared it already because I'm trying to update my whole 1.18 modpack, so even if it's not an important mod I will add it as it's already for the new version

**Comment by AlasDiablo** [comment]
A fix is available (version [5.5.28](https://www.curseforge.com/minecraft/mc-mods/diabololib/files/3904234)) for forge 41.1.0

**Comment by emanuele246gi** [comment]
Thank you man!
